const customers=[
 {id:'LTT-48291',name:'سالم الورفلي',segment:'أعمال / ذهبي',plan:'بيزنس برو',arpu:680,tenure:'42 شهرًا',usage:'−43%',complaints:4,prob:92,risk:'high',action:'تدخل فوري + مدير حساب',region:'طرابلس'},
 {id:'LTT-19375',name:'هند الزوي',segment:'فردي / بلاتيني',plan:'فايبر ماكس',arpu:420,tenure:'28 شهرًا',usage:'−36%',complaints:3,prob:87,risk:'high',action:'حل مشكلة الجودة',region:'بنغازي'},
 {id:'LTT-77420',name:'مؤسسة الأفق',segment:'أعمال / فضي',plan:'بيزنس برو',arpu:895,tenure:'19 شهرًا',usage:'−29%',complaints:5,prob:83,risk:'high',action:'تدخل فوري + عرض مخصص',region:'مصراتة'},
 {id:'LTT-31684',name:'آية المغربي',segment:'فردي / ذهبي',plan:'موبايل بلس',arpu:215,tenure:'35 شهرًا',usage:'−31%',complaints:2,prob:78,risk:'high',action:'ترقية الباقة',region:'طرابلس'},
 {id:'LTT-65091',name:'عمر الفيتوري',segment:'فردي / فضي',plan:'فايبر ماكس',arpu:310,tenure:'12 شهرًا',usage:'−22%',complaints:2,prob:68,risk:'medium',action:'عرض خصم مخصص',region:'الجنوب'},
 {id:'LTT-22943',name:'شركة المدار',segment:'أعمال / ذهبي',plan:'بيزنس برو',arpu:740,tenure:'26 شهرًا',usage:'−19%',complaints:1,prob:61,risk:'medium',action:'التواصل مع العميل',region:'بنغازي'},
 {id:'LTT-91204',name:'خالد الترهوني',segment:'فردي / فضي',plan:'موبايل بلس',arpu:150,tenure:'8 أشهر',usage:'−14%',complaints:0,prob:31,risk:'low',action:'لا حاجة لتدخل',region:'طرابلس'}];
const drivers=[['انخفاض الاستخدام الشهري',87],['تكرار الشكاوى',73],['التأخر في الدفع',61],['جودة الشبكة',49]];
const el=id=>document.getElementById(id); const format=n=>new Intl.NumberFormat('ar-LY').format(n);
function initials(name){return name.split(' ').slice(0,2).map(x=>x[0]).join('')}
function renderRows(data){el('customerRows').innerHTML=data.slice(0,5).map(c=>`<tr><td><div class="customer-name"><span class="avatar">${initials(c.name)}</span><div>${c.name}<small style="display:block;color:#8291a6;font-weight:400;margin-top:3px">${c.id}</small></div></div></td><td>${c.segment}</td><td>${c.plan}</td><td>${format(c.arpu)} د.ل</td><td>${c.tenure}</td><td class="usage">${c.usage}</td><td>${c.complaints}</td><td><b>${c.prob}%</b></td><td><span class="risk-tag ${c.risk}">${c.risk==='high'?'مرتفع':c.risk==='medium'?'متوسط':'منخفض'}</span></td><td class="action">${c.action}</td><td><button class="row-btn" aria-label="تفاصيل العميل"><i class="fa-solid fa-ellipsis"></i></button></td></tr>`).join('');el('shownCount').textContent=Math.min(5,data.length)}
function renderDrivers(){el('driversList').innerHTML=drivers.map(d=>`<div class="driver"><span>${d[0]}</span><div class="track"><div class="fill" style="width:${d[1]}%"></div></div><b>${d[1]}%</b></div>`).join('')}
function renderSegments(){const seg=[['أعمال / ذهبي',12.6],['فردي / بلاتيني',9.8],['فردي / ذهبي',7.1],['فردي / فضي',4.4]];el('segmentChart').innerHTML=seg.map(s=>`<div class="segment"><span>${s[0]}</span><div class="track"><div class="fill" style="width:${s[1]/13*100}%"></div></div><b>${s[1]}%</b></div>`).join('')}
function trend(){const svg=el('trendChart'), w=720,h=250,left=43,bottom=32,top=18,right=18;const actual=[5.1,5.6,5.4,6.1,6.5,6.2,6.8,7.1,7.5,7.8],predict=[7.8,8.1,8.5,8.2],months=['نوف','ديس','ينا','فبر','مار','أبر','ماي','يون','يول','أغ','سب','أكت','نوف'];const all=actual.concat(predict.slice(1));const x=i=>left+i*(w-left-right)/(months.length-1),y=v=>top+(9-v)*(h-top-bottom)/5;let out='';[4,5,6,7,8,9].forEach(v=>out+=`<line x1="${left}" x2="${w-right}" y1="${y(v)}" y2="${y(v)}" stroke="#e7edf5"/><text x="${left-9}" y="${y(v)+4}" text-anchor="end" fill="#7a8ba3" font-size="10">${v}%</text>`);months.forEach((m,i)=>out+=`<text x="${x(i)}" y="${h-8}" text-anchor="middle" fill="#7a8ba3" font-size="10">${m}</text>`);const path=a=>a.map((v,i)=>`${i?'L':'M'}${x(i)},${y(v)}`).join(' ');out+=`<path d="${path(actual)}" fill="none" stroke="#0057b8" stroke-width="3"/><path d="${predict.map((v,i)=>`${i?'L':'M'}${x(i+9)},${y(v)}`).join(' ')}" fill="none" stroke="#00a6a6" stroke-width="3" stroke-dasharray="6 5"/>`;all.forEach((v,i)=>out+=`<circle class="point" data-i="${i}" cx="${x(i)}" cy="${y(v)}" r="4" fill="${i<10?'#0057b8':'#00a6a6'}" stroke="white" stroke-width="2"/>`);out+=`<line x1="${x(9)}" x2="${x(9)}" y1="${top}" y2="${h-bottom}" stroke="#91a5bd" stroke-dasharray="3 4"/><text x="${x(9)+4}" y="${top+11}" fill="#71839b" font-size="9">اليوم</text>`;svg.innerHTML=out;svg.querySelectorAll('.point').forEach(p=>p.addEventListener('mouseenter',e=>{let i=+p.dataset.i;let t=el('chartTip');t.textContent=`${months[i]}: ${all[i]}%`;t.style.display='block';t.style.right=`${Math.max(5,100-(x(i)/w*100))}%`;t.style.top=`${y(all[i])-6}px`}));svg.addEventListener('mouseleave',()=>el('chartTip').style.display='none')}
function filter(){const r=el('risk').value,reg=el('region').value,p=el('plan').value,q=el('search').value.trim();let out=customers.filter(c=>(r==='all'||c.risk===r)&&(reg==='all'||c.region===reg)&&(p==='all'||c.plan===p)&&(!q||c.id.includes(q)||c.name.includes(q)));renderRows(out);const high=out.filter(c=>c.risk==='high').length;el('customerCount').textContent=format(48274);el('riskCount').textContent=format(Math.round(3767*(out.length/customers.length)));el('revenueRisk').textContent=(1.24*(out.length/customers.length||0)).toFixed(2)+' م.د.ل';}
function toast(msg){const t=el('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
['risk','region','plan','search'].forEach(id=>el(id).addEventListener(id==='search'?'input':'change',filter));el('reset').onclick=()=>{['risk','region','plan'].forEach(id=>el(id).value='all');el('search').value='';filter();toast('تمت إعادة ضبط جميع المرشحات')};document.querySelectorAll('[data-risk]').forEach(b=>b.onclick=()=>{el('risk').value=b.dataset.risk;filter();document.getElementById('customers').scrollIntoView({behavior:'smooth'})});el('summaryBtn').onclick=()=>toast('ملخص ذكي: ارتفاع الخطر يتركز في عملاء الأعمال ذوي الشكاوى المفتوحة.');el('campaignBtn').onclick=()=>toast('تم إنشاء حملة احتفاظ لـ 128 عميلًا من ذوي الأولوية القصوى.');el('insightBtn').onclick=()=>{el('risk').value='high';filter();el('customers').scrollIntoView({behavior:'smooth'})};renderRows(customers);renderDrivers();renderSegments();trend();
